### ISSUE TITLE
TypeError: sequence item 0: expected str instance, list found

### ISSUE THREAD

**Issue by thommahoney** [tiiuae/sbomnix#79]
When running sbomnix, I get the following error:

```
Traceback (most recent call last):
  File "/nix/store/mzck8rim82y9vx4xm18dp312gn88vni2-python3.10-sbomnix-1.4.6/bin/.sbomnix-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/mzck8rim82y9vx4xm18dp312gn88vni2-python3.10-sbomnix-1.4.6/lib/python3.10/site-packages/sbomnix/main.py", line 100, in main
    sbomdb = SbomDb(target_path, runtime, buildtime, args.meta, args.depth)
  File "/nix/store/mzck8rim82y9vx4xm18dp312gn88vni2-python3.10-sbomnix-1.4.6/lib/python3.10/site-packages/sbomnix/sbomdb.py", line 55, in __init__
    self._init_sbomdb()
  File "/nix/store/mzck8rim82y9vx4xm18dp312gn88vni2-python3.10-sbomnix-1.4.6/lib/python3.10/site-packages/sbomnix/sbomdb.py", line 105, in _init_sbomdb
    self._sbomdb_join_meta(self.meta_path)
  File "/nix/store/mzck8rim82y9vx4xm18dp312gn88vni2-python3.10-sbomnix-1.4.6/lib/python3.10/site-packages/sbomnix/sbomdb.py", line 116, in _sbomdb_join_meta
    df_meta = _parse_json_metadata(meta_path)
  File "/nix/store/mzck8rim82y9vx4xm18dp312gn88vni2-python3.10-sbomnix-1.4.6/lib/python3.10/site-packages/sbomnix/sbomdb.py", line 471, in _parse_json_metadata
    setcol("meta_maintainers_email", []).append(";".join(emails))
TypeError: sequence item 0: expected str instance, list found
```

The json metadata was created using the following command:

```shell
nix-env -qa --meta --json '.*' > ~/nix-meta.json
```

In case it's important, I invoked sbomnix using the following command:

```shell
nix run github:tiiuae/sbomnix#sbomnix -- $(readlink result) --type=both --meta=nix-meta.json
```

**Comment by henrirosten** [comment]
@thommahoney : thanks for reporting this issue.
Can you verify if https://github.com/tiiuae/sbomnix/pull/80 fixes the issue?

**Comment by henrirosten** [comment]
Fixed by PR https://github.com/tiiuae/sbomnix/pull/80, which is now merged in main.
